---
- name: Include vars
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set controller hostname
      ansible.builtin.set_fact:
        controller_host: 'aap-controller.int'
        hub_host: 'aap-hub.int'
      tags: always

    - name: Include all vars
      ansible.builtin.include_vars: all_objects_set_empty
      tags: always

#    - name: Include objects
#      ansible.builtin.include_vars:
#        dir: objects
#        extensions:
#          - ''
#      tags: always

- name: Run playbook to configure AAP
  import_playbook: configify.aapconfig.aap_configure.yml
